export const types = {
    GET_DEVICES_LIST: 'GET_DEVICES_LIST',
    SET_CURRENT_DEVICE: 'SET_CURRENT_DEVICE',
    GET_LIST_CONTENTS: 'GET_LIST_CONTENTS',
    SET_FILTER_TYPE: 'SET_FILTER_TYPE',
    SET_VIEW_TYPE: 'SET_VIEW_TYPE',
    SET_SORT_TYPE: 'SET_SORT_TYPE',
    GET_DEVICE_PROPERTIES: 'GET_DEVICE_PROPERTIES',
    GET_IMAGES_LIST: 'GET_IMAGES_LIST'
}